import { GachaItem, ScriptureQuote, Banner, LeaderboardPlayer } from './types';
import nurseElfeAngelicImg from './assets/images/nurse_elfe_angelic_1786227050228.jpg';
import nurseElfeHeroicImg from './assets/images/nurse_elfe_heroic_1786227064218.jpg';

export const DAILY_SCRIPTURES: ScriptureQuote[] = [
  {
    id: '1',
    reference: '3 John 1:2',
    verse: 'Beloved, I pray that all may go well with you and that you may be in good health, as it goes well with your soul.',
    reflection: 'Wholeness encompasses both body and spirit. Take time today to care for your physical temple and nurture peace in your heart.',
    category: 'Healing',
  },
  {
    id: '2',
    reference: 'Psalm 103:2-3',
    verse: 'Bless the Lord, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases.',
    reflection: 'Gratitude renews our mindset and rests our nervous system. A thankful spirit promotes bodily restoration.',
    category: 'Healing',
  },
  {
    id: '3',
    reference: 'Isaiah 40:29-31',
    verse: 'He gives power to the faint, and to him who has no might he increases strength.',
    reflection: 'When physical energy runs low, spiritual strength provides a quiet, enduring reservoir.',
    category: 'Strength',
  },
  {
    id: '4',
    reference: 'Philippians 4:6-7',
    verse: 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.',
    reflection: 'Deep breathing combined with mindful prayer reduces cortisol and helps maintain cardiovascular balance.',
    category: 'Peace',
  },
  {
    id: '5',
    reference: 'Proverbs 17:22',
    verse: 'A joyful heart is good medicine, but a crushed spirit dries up the bones.',
    reflection: 'Joy and laughter stimulate healthy circulatory flow and uplift emotional well-being.',
    category: 'Renewal',
  },
];

export const GACHA_CATALOG: GachaItem[] = [
  // CHARACTERS (SSR)
  {
    id: 'elfe-angelic',
    name: 'Nurse Elfe (Angelic Medic)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 1000,
    characterName: 'Elfe',
    description: 'Exclusive angelic nurse outfit featuring glowing radiant wings and medical staff.',
    image: nurseElfeAngelicImg,
  },
  {
    id: 'elfe-heroic',
    name: 'Nurse Elfe (Heroic Arrival)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 900,
    characterName: 'Elfe',
    description: 'The iconic emergency response suit designed for heroic high-precision care.',
    image: nurseElfeHeroicImg,
  },
  {
    id: 'seraphina-healer',
    name: 'Seraphina (Celestial Star Healer)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 1100,
    characterName: 'Seraphina',
    description: 'High Priestess of Divine Healing who wields starlight to restore body and spirit.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SeraphinaCelestialStarHealer',
  },
  {
    id: 'doctor-kenji',
    name: 'Doctor Kenji (Divine Light Surgeon)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 1050,
    characterName: 'Kenji',
    description: 'Master surgeon guided by holy wisdom, performing flawless medical restoration.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=DoctorKenjiDivineSurgeon',
  },
  {
    id: 'aoi-hydration',
    name: 'Aoi (Hydration Spirit Maiden)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 980,
    characterName: 'Aoi',
    description: 'Spirit of pure living spring waters who purifies and quenches spiritual thirst.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=AoiHydrationSpiritMaiden',
  },
  {
    id: 'lumina-priestess',
    name: 'Lumina (Solar Sanctuary Priestess)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 1020,
    characterName: 'Lumina',
    description: 'Radiantly energetic healer harnessing morning sunlight for cellular renewal.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=LuminaSolarPriestess',
  },
  {
    id: 'kaito-paladin',
    name: 'Kaito (Holy Sword Medic)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 960,
    characterName: 'Kaito',
    description: 'Defender of the weak who wields both a holy blade and restorative ointment.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=KaitoHolySwordMedic',
  },
  {
    id: 'amara-botanist',
    name: 'Amara (Sacred Herb Botanist)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 940,
    characterName: 'Amara',
    description: 'Expert in biblical flora, wild honey, and natural healing oils.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=AmaraSacredHerbBotanist',
  },

  // CHARACTERS & OUTFITS (SR)
  {
    id: 'nurse-chloe',
    name: 'Chloe (Vitality Android Medic)',
    type: 'character',
    rarity: 'SR',
    rarityScore: 400,
    characterName: 'Chloe',
    description: 'Futuristic medical specialist with instant biometric scanning precision.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=NurseChloeVitalityAndroid',
  },
  {
    id: 'brother-gabriel',
    name: 'Brother Gabriel (Faith Guardian)',
    type: 'character',
    rarity: 'SR',
    rarityScore: 380,
    characterName: 'Gabriel',
    description: 'Devout temple guardian leading daily scripture meditation and prayer.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=BrotherGabrielFaithGuardian',
  },
  {
    id: 'mayumi-caregiver',
    name: 'Mayumi (Cherry Blossom Caregiver)',
    type: 'character',
    rarity: 'SR',
    rarityScore: 360,
    characterName: 'Mayumi',
    description: 'Gentle clinic nurse offering comforting herbal teas and soothing music.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=MayumiCherryBlossomNurse',
  },
  {
    id: 'elfe-casual',
    name: 'Elfe (Off-Duty Casual)',
    type: 'outfit',
    rarity: 'SR',
    rarityScore: 350,
    characterName: 'Elfe',
    description: 'A cozy cardigan and glasses worn during study and wellness research.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=NurseElfeCasualGlasses',
  },
  {
    id: 'outfit-summer',
    name: 'Nurse Elfe (Breeze Uniform)',
    type: 'outfit',
    rarity: 'SR',
    rarityScore: 300,
    characterName: 'Elfe',
    description: 'Lightweight breathable scrub outfit for warm summer shifts.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=NurseElfeBreezeUniform',
  },

  // ACCESSORIES (SSR)
  {
    id: 'accessory-stethoscope',
    name: 'Golden Stethoscope of Grace',
    type: 'accessory',
    rarity: 'SSR',
    rarityScore: 800,
    characterName: 'Universal',
    description: 'Precision acoustic stethoscope crafted with an elegant gold trim.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=GoldenStethoscopeGrace',
  },
  {
    id: 'accessory-wings',
    name: 'Feathered Seraph Wings',
    type: 'accessory',
    rarity: 'SSR',
    rarityScore: 850,
    characterName: 'Universal',
    description: 'Luminous wings that shimmer softly during wellness consultations.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=FeatheredSeraphWingsGlow',
  },
  {
    id: 'accessory-ring-vitality',
    name: 'Sapphire Ring of Vitality',
    type: 'accessory',
    rarity: 'SSR',
    rarityScore: 820,
    characterName: 'Universal',
    description: 'Anointed gemstone ring that enhances focus during prayer and exercise.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=SapphireRingVitality',
  },
  {
    id: 'accessory-olive-pendant',
    name: 'Anointed Olive Branch Pendant',
    type: 'accessory',
    rarity: 'SSR',
    rarityScore: 810,
    characterName: 'Universal',
    description: 'Pendant made from olive wood from Galilee, symbol of peace and health.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=AnointedOliveBranchPendant',
  },

  // ACCESSORIES (SR)
  {
    id: 'accessory-heart-monitor',
    name: 'Holographic Heart Monitor',
    type: 'accessory',
    rarity: 'SR',
    rarityScore: 320,
    characterName: 'Universal',
    description: 'Wearable HUD wristband tracking real-time pulse and blood pressure.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=HolographicHeartMonitor',
  },
  {
    id: 'accessory-herb-satchel',
    name: 'Emerald Herb Satchel',
    type: 'accessory',
    rarity: 'SR',
    rarityScore: 310,
    characterName: 'Universal',
    description: 'Woven pouch containing aromatic frankincense, myrrh, and mint.',
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=EmeraldHerbSatchel',
  },
  {
    id: 'accessory-silver-chime',
    name: 'Purity Silver Chime',
    type: 'accessory',
    rarity: 'SR',
    rarityScore: 290,
    characterName: 'Universal',
    description: 'Resonant bell used to mark scripture meditation sessions.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=PuritySilverChime',
  },

  // ACCESSORIES (R)
  {
    id: 'accessory-kit',
    name: 'First-Aid Tech Pouch',
    type: 'accessory',
    rarity: 'R',
    rarityScore: 100,
    characterName: 'Universal',
    description: 'Compact medical kit equipped with digital vital sensors.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=FirstAidTechPouch',
  },
  {
    id: 'accessory-clipboard',
    name: 'Holographic Medical Chart',
    type: 'accessory',
    rarity: 'R',
    rarityScore: 120,
    characterName: 'Universal',
    description: 'Interactive tablet display that logs daily vitals and trends.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=HolographicMedicalChart',
  },
  {
    id: 'accessory-water-flask',
    name: 'Sanctified Water Flask',
    type: 'accessory',
    rarity: 'R',
    rarityScore: 110,
    characterName: 'Universal',
    description: 'Durable thermal container keeping spring water cool for hours.',
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=SanctifiedWaterFlask',
  },
];

export const BANNERS: Banner[] = [
  {
    id: 'angelic-medic',
    title: 'Angelic Medics & Celestials',
    subtitle: 'Featured Rate-Up for Seraphina Star Healer & Nurse Elfe Angelic Form',
    featuredName: 'Seraphina & Nurse Elfe',
    featuredRarity: 'SSR',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SeraphinaCelestialStarHealer',
    costSingle: 160,
    costMulti: 1500,
    isLimited: true,
  },
  {
    id: 'divine-surgeons',
    title: 'Divine Surgeons & Holy Paladins',
    subtitle: 'Featured Rate-Up for Doctor Kenji & Kaito Sword Medic',
    featuredName: 'Doctor Kenji (SSR)',
    featuredRarity: 'SSR',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=DoctorKenjiDivineSurgeon',
    costSingle: 160,
    costMulti: 1500,
    isLimited: true,
  },
  {
    id: 'botanist-spirits',
    title: 'Sacred Botanists & Hydration Spirits',
    subtitle: 'Featured Rate-Up for Amara Herb Botanist & Aoi Water Maiden',
    featuredName: 'Aoi & Amara (SSR)',
    featuredRarity: 'SSR',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=AoiHydrationSpiritMaiden',
    costSingle: 160,
    costMulti: 1500,
    isLimited: false,
  },
  {
    id: 'heroic-arrival',
    title: 'All-Star Anime Heroes & Relics',
    subtitle: 'Welcome Banner with boosted drop rates for characters and accessories',
    featuredName: 'Lumina & All Heroes',
    featuredRarity: 'SSR',
    image: nurseElfeHeroicImg,
    costSingle: 160,
    costMulti: 1500,
    isLimited: false,
  },
];

export const INITIAL_LEADERBOARD: LeaderboardPlayer[] = [
  {
    id: 'p1',
    name: 'GraceKeeper99',
    rank: 1,
    powerScore: 14800,
    unlockedCount: 24,
    avatar: nurseElfeAngelicImg,
    badge: 'Angel Rank I',
  },
  {
    id: 'p2',
    name: 'YahushaFaithful',
    rank: 2,
    powerScore: 12350,
    unlockedCount: 19,
    avatar: nurseElfeHeroicImg,
    badge: 'Angel Rank II',
  },
  {
    id: 'p3',
    name: 'SeraphNurse',
    rank: 3,
    powerScore: 11100,
    unlockedCount: 16,
    avatar: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SeraphNurseAnime',
    badge: 'Angel Rank III',
  },
  {
    id: 'p4',
    name: 'WellnessSeeker',
    rank: 4,
    powerScore: 8900,
    unlockedCount: 14,
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=WellnessSeekerWaifu',
    badge: 'Guardian',
  },
  {
    id: 'p5',
    name: 'ShalomPioneer',
    rank: 5,
    powerScore: 7800,
    unlockedCount: 12,
    avatar: 'https://api.dicebear.com/7.x/lorelei/svg?seed=ShalomPioneerAnime',
    badge: 'Guardian',
  },
  {
    id: 'p6',
    name: 'VitalPulse_User',
    rank: 6,
    powerScore: 6500,
    unlockedCount: 10,
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=VitalPulseAnime',
    badge: 'Caregiver',
  },
];
