import { GachaItem, ScriptureQuote, Banner, LeaderboardPlayer } from './types';
import nurseElfeAngelicImg from './assets/images/nurse_elfe_angelic_1786227050228.jpg';
import nurseElfeHeroicImg from './assets/images/nurse_elfe_heroic_1786227064218.jpg';

export const DAILY_SCRIPTURES: ScriptureQuote[] = [
  {
    id: '1',
    reference: '3 John 1:2',
    verse: 'Beloved, I pray that all may go well with you and that you may be in good health, as it goes well with your soul.',
    reflection: 'Wholeness encompasses both body and spirit. Take time today to care for your physical temple and nurture peace in your heart.',
    category: 'Healing',
  },
  {
    id: '2',
    reference: 'Psalm 103:2-3',
    verse: 'Bless the Lord, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases.',
    reflection: 'Gratitude renews our mindset and rests our nervous system. A thankful spirit promotes bodily restoration.',
    category: 'Healing',
  },
  {
    id: '3',
    reference: 'Isaiah 40:29-31',
    verse: 'He gives power to the faint, and to him who has no might he increases strength.',
    reflection: 'When physical energy runs low, spiritual strength provides a quiet, enduring reservoir.',
    category: 'Strength',
  },
  {
    id: '4',
    reference: 'Philippians 4:6-7',
    verse: 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.',
    reflection: 'Deep breathing combined with mindful prayer reduces cortisol and helps maintain cardiovascular balance.',
    category: 'Peace',
  },
  {
    id: '5',
    reference: 'Proverbs 17:22',
    verse: 'A joyful heart is good medicine, but a crushed spirit dries up the bones.',
    reflection: 'Joy and laughter stimulate healthy circulatory flow and uplift emotional well-being.',
    category: 'Renewal',
  },
];

export const GACHA_CATALOG: GachaItem[] = [
  {
    id: 'elfe-angelic',
    name: 'Nurse Elfe (Angelic Medic)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 1000,
    characterName: 'Elfe',
    description: 'Exclusive angelic nurse outfit featuring glowing radiant wings and medical staff.',
    image: nurseElfeAngelicImg,
  },
  {
    id: 'elfe-heroic',
    name: 'Nurse Elfe (Heroic Arrival)',
    type: 'character',
    rarity: 'SSR',
    rarityScore: 900,
    characterName: 'Elfe',
    description: 'The iconic emergency response suit designed for heroic high-precision care.',
    image: nurseElfeHeroicImg,
  },
  {
    id: 'elfe-casual',
    name: 'Elfe (Off-Duty Casual)',
    type: 'outfit',
    rarity: 'SR',
    rarityScore: 350,
    characterName: 'Elfe',
    description: 'A cozy cardigan and glasses worn during study and wellness research.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=NurseElfeCasualGlasses',
  },
  {
    id: 'accessory-stethoscope',
    name: 'Golden Stethoscope of Grace',
    type: 'accessory',
    rarity: 'SSR',
    rarityScore: 800,
    characterName: 'Elfe',
    description: 'Precision acoustic stethoscope crafted with an elegant gold trim.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=GoldenStethoscope',
  },
  {
    id: 'accessory-wings',
    name: 'Feathered Seraph Wings',
    type: 'accessory',
    rarity: 'SSR',
    rarityScore: 850,
    characterName: 'Elfe',
    description: 'Luminous wings that shimmer softly during wellness consultations.',
    image: 'https://api.dicebear.com/7.x/lorelei/svg?seed=FeatheredSeraphWings',
  },
  {
    id: 'outfit-summer',
    name: 'Nurse Elfe (Breeze Uniform)',
    type: 'outfit',
    rarity: 'SR',
    rarityScore: 300,
    characterName: 'Elfe',
    description: 'Lightweight breathable scrub outfit for warm summer shifts.',
    image: 'https://api.dicebear.com/7.x/adventurer/svg?seed=NurseElfeBreezeUniform',
  },
  {
    id: 'accessory-kit',
    name: 'First-Aid Tech Pouch',
    type: 'accessory',
    rarity: 'R',
    rarityScore: 100,
    characterName: 'Elfe',
    description: 'Compact medical kit equipped with digital vital sensors.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=FirstAidTechPouch',
  },
  {
    id: 'accessory-clipboard',
    name: 'Holographic Medical Chart',
    type: 'accessory',
    rarity: 'R',
    rarityScore: 120,
    characterName: 'Elfe',
    description: 'Interactive tablet display that logs daily vitals and trends.',
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=HolographicMedicalChart',
  },
];

export const BANNERS: Banner[] = [
  {
    id: 'angelic-medic',
    title: 'The First Angelic Medic',
    subtitle: 'Limited Event Banner featuring Nurse Elfe Angelic Form',
    featuredName: 'Nurse Elfe (Angelic Medic)',
    featuredRarity: 'SSR',
    image: nurseElfeAngelicImg,
    costSingle: 160,
    costMulti: 1500,
    isLimited: true,
  },
  {
    id: 'heroic-arrival',
    title: 'The Heroic Arrival',
    subtitle: 'Welcome Starter Banner with boosted drop rates for starter gear',
    featuredName: 'Nurse Elfe (Heroic Arrival)',
    featuredRarity: 'SSR',
    image: nurseElfeHeroicImg,
    costSingle: 160,
    costMulti: 1500,
    isLimited: false,
  },
];

export const INITIAL_LEADERBOARD: LeaderboardPlayer[] = [
  {
    id: 'p1',
    name: 'GraceKeeper99',
    rank: 1,
    powerScore: 14800,
    unlockedCount: 24,
    avatar: nurseElfeAngelicImg,
    badge: 'Angel Rank I',
  },
  {
    id: 'p2',
    name: 'YahushaFaithful',
    rank: 2,
    powerScore: 12350,
    unlockedCount: 19,
    avatar: nurseElfeHeroicImg,
    badge: 'Angel Rank II',
  },
  {
    id: 'p3',
    name: 'SeraphNurse',
    rank: 3,
    powerScore: 11100,
    unlockedCount: 16,
    avatar: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SeraphNurseAnime',
    badge: 'Angel Rank III',
  },
  {
    id: 'p4',
    name: 'WellnessSeeker',
    rank: 4,
    powerScore: 8900,
    unlockedCount: 14,
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=WellnessSeekerWaifu',
    badge: 'Guardian',
  },
  {
    id: 'p5',
    name: 'ShalomPioneer',
    rank: 5,
    powerScore: 7800,
    unlockedCount: 12,
    avatar: 'https://api.dicebear.com/7.x/lorelei/svg?seed=ShalomPioneerAnime',
    badge: 'Guardian',
  },
  {
    id: 'p6',
    name: 'VitalPulse_User',
    rank: 6,
    powerScore: 6500,
    unlockedCount: 10,
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=VitalPulseAnime',
    badge: 'Caregiver',
  },
];
